apiVersion: apps/v1
kind: Deployment
metadata:
  name: timefeed
  namespace: web
  labels:
    app: timefeed
spec:
  selector:
    matchLabels:
      app: timefeed
  template:
    metadata:
      labels:
        app: timefeed
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "timefeed"
        dapr.io/app-port: "8080"
        dapr.io/config: "appconfig"
        dapr.io/log-as-json: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"
    spec:
      containers:
      - name: timefeed
        image: hitoshiresearch.azurecr.io/dapr-sample/timefeed:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: azure
        - name: SPRING_MAIN_BANNER-MODE
          value: "off"
