server:
  port: 8080

backend:
  timefeedHost: ${TIMEFEED_HOST:http://localhost:8088}
  timefeedBase: ${TIMEFEED_BASE:/}
  orderTopicHost: ${ORDER_TOPIC_HOST:http://localhost:3000}
  orderTopicBase: ${ORDER_TOPIC_BASE:/consumers/simple}

aggregator:
  titleVersion: ${TITLE_VERSION:}